<?php

define('PUSHER_APP_ID', $_ENV['PUSHER_APP_ID']);
define('PUSHER_APP_KEY', $_ENV['PUSHER_APP_KEY']);
define('PUSHER_APP_SECRET', $_ENV['PUSHER_APP_SECRET']);
define('PUSHER_APP_CLUSTER', $_ENV['PUSHER_APP_CLUSTER']);
